name: mongo_dart
description: MongoDB driver for Dart
version: 0.0.10
authors: 
  - Vadim Tsushko <vadimtsushko@gmail.com>
  - Ted Sander <ted@tedsander.com>
homepage: https://github.com/vadimtsushko/mongo_dart
dependencies:
 unittest: any
 args: any
 logging: any
 meta: any